### ISSUE TITLE
Where to add ASP.NET Core Identity package for Role based access?

### ISSUE THREAD

**Issue by TejasCMehta** [oznakdn/ProjectManagement#1]
Hi Ozan!

Great piece of code you have put for community, I really like your code which has DRY and SOLID principles. 

I am taking this architecture as base code for my next project but not sure where to put ASP.NET Identity Classes as I want to use IdentityUser and IdentityRole in the system.

One approach is to create seperate layer inside Infra folder like below:

<img width="186" alt="image" src="https://user-images.githubusercontent.com/5519037/234243555-aff60fdd-8128-4650-822e-01c3dbe13e6b.png">

Then issue is how can I establish relationship with Domain Entities like Employees with ApplicationUser ( Inheriting IdentityUser) ?

**Comment by oznakdn** [comment]
First of all, I'm sorry for the late response to your question. If you are going to use microsoft's identity package. You must install the relevant package on the Domain layer under the Core layer.
